### ISSUE TITLE
Support for invoice without amount

### ISSUE THREAD

**Issue by bota87** [lnbits/lndhub#14]
When I click on receive on Zeus wallet without giving an amount I get an error, this works with LN bank and getalby.
`2023-08-04 19:52:53.17 | INFO | 195.231.120.110:0 - "POST /lndhub/ext/addinvoice HTTP/1.1" 404`

When I try to pay an invoice generated without an amount Zeus first ask for the amount to pay than give an error
`2023-08-04 20:01:12.06 | INFO | 195.231.120.110:0 - "POST /lndhub/ext/payinvoice HTTP/1.1" 404`

**Comment by callebtc** [comment]
LNbits does not support invoices without amounts and there are currently no plans to implement it ... sry!
