### ISSUE TITLE
Bluewallet API and error handling

### ISSUE THREAD

**Issue by limpbrains** [lnbits/lndhub#20]
When I'm tyring to pay invoice with amount bigger than I have, LNbits returns 404 error with json body: 
`{"detail": "Payment failed"}`

Bluewallet expects json to contain error field in case of the error
https://github.com/BlueWallet/BlueWallet/blob/2ea7a17bb6d0651cf84426f9d2ca2817bc78cd3b/class/wallets/lightning-custodian-wallet.js#L137

I can fix this by changing BW, but it feels like this issue should also be fixed in lnbits/lndhub 

related https://github.com/BlueWallet/BlueWallet/issues/5597

**Comment by dni** [comment]
return `{"error": "payment failed"}` with status 200 seems to work for Zeus can you try  it for bluewallet? 
https://github.com/lnbits/lndhub/pull/22

**Comment by limpbrains** [comment]
Yes, it should work. Can't test it right now, but looking at the BW code, I can say so
