### ISSUE TITLE
Timestamp showing up as string instead of epoch time

### ISSUE THREAD

**Issue by Amperstrand** [lnbits/lndhub#38]
gettxs and getuserinvoices are returning strings instead of epoch time:

```
  "description": "Paid to dummy (Order ID: YDCMSd7LCB4dn6w63kaNz4)",
    "payment_hash": "",
    "ispaid": true,
    "amt": 8,
    "expire_time": 1731598827,
    "timestamp": "2024-11-14T15:02:34.532574+00:00",
    "type": "user_invoice"
```

The code responsible for this is [here](https://github.com/lnbits/lndhub/blob/7bb4856ed81abf3742a6d035a6217288babe307a/views_api.py#L109) and [here](https://github.com/lnbits/lndhub/blob/7bb4856ed81abf3742a6d035a6217288babe307a/views_api.py#L148).

This is testing lnbits 1.0.0rc5 with some minor changes. It could be that I am causing this issue because of some changes that I am experimenting with, but pretty sure that I am getting a string instead of an expected int

```
 "timestamp": payment.time,
```

**Comment by Amperstrand** [comment]
```
"detail": "int() argument must be a string, a bytes-like object or a real number, not 'datetime.datetime'"
```
looks like its not a string but a datetime.datetime

This fixes it for now:

```
"timestamp": payment.time if isinstance(payment.time, int) else int(payment.time.timestamp()),
```

Doing this instead changes it back to a timestamp so that it works. But is this the correct approach or should payment.time be epoch time in the first place.

**Comment by dni** [comment]
yes, this is an issue i but it onto the todolist for v1 release
